# Generated by Django 4.2.21 on 2025-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binstatus',
            name='bin_type',
        ),
        migrations.RemoveField(
            model_name='binstatus',
            name='device',
        ),
        migrations.RemoveField(
            model_name='binstatus',
            name='is_full',
        ),
        migrations.AddField(
            model_name='binstatus',
            name='bio_status',
            field=models.CharField(choices=[('not full', 'Not Full'), ('full', 'Full')], default='not full', max_length=20),
        ),
        migrations.AddField(
            model_name='binstatus',
            name='recyclable_status',
            field=models.CharField(choices=[('not full', 'Not Full'), ('full', 'Full')], default='not full', max_length=20),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
